#!/bin/bash
set -euo pipefail
zip=$1
target=$2

 function mv_if_exist() {
    if [[ -f $1 || -d $1 ]]; then
      mv $1 $2  
    fi
}

if [[ -f $zip ]]; then
  temp_dir=`mktemp -d`
  echo "Creating temp dir: $temp_dir"
  unzip "$zip" -d $temp_dir > /dev/null
  full_path=$temp_dir/$(basename "$zip")
  echo "Converting pack.mcmeta..."
  sed -i 's/[0-9],/6,/' $temp_dir/pack.mcmeta
  echo "Converting directories..."
  mv_if_exist "$temp_dir/assets/minecraft/textures/blocks" "$temp_dir/assets/minecraft/textures/block"
  mv_if_exist "$temp_dir/assets/minecraft/textures/items" "$temp_dir/assets/minecraft/textures/item"
  mv_if_exist "$temp_dir/assets/minecraft/textures/gui/achievement" "$temp_dir/assets/minecraft/textures/gui/advancements"
  echo "Converting textures..."
  ## wool
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_red.png" "$temp_dir/assets/minecraft/textures/block/red_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_blue.png" "$temp_dir/assets/minecraft/textures/block/blue_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_cyan.png" "$temp_dir/assets/minecraft/textures/block/cyan_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_gray.png" "$temp_dir/assets/minecraft/textures/block/gray_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_lime.png" "$temp_dir/assets/minecraft/textures/block/lime_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_pink.png" "$temp_dir/assets/minecraft/textures/block/pink_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_black.png" "$temp_dir/assets/minecraft/textures/block/black_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_brown.png" "$temp_dir/assets/minecraft/textures/block/brown_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_green.png" "$temp_dir/assets/minecraft/textures/block/green_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_white.png" "$temp_dir/assets/minecraft/textures/block/white_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_orange.png" "$temp_dir/assets/minecraft/textures/block/orange_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_purple.png" "$temp_dir/assets/minecraft/textures/block/purple_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_yellow.png" "$temp_dir/assets/minecraft/textures/block/yellow_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_magenta.png" "$temp_dir/assets/minecraft/textures/block/magenta_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_light_blue.png" "$temp_dir/assets/minecraft/textures/block/light_blue_wool.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wool_colored_silver.png" "$temp_dir/assets/minecraft/textures/block/light_gray_wool.png"
  ## glass
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_red.png" "$temp_dir/assets/minecraft/textures/block/red_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_blue.png" "$temp_dir/assets/minecraft/textures/block/blue_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_cyan.png" "$temp_dir/assets/minecraft/textures/block/cyan_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_gray.png" "$temp_dir/assets/minecraft/textures/block/gray_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_lime.png" "$temp_dir/assets/minecraft/textures/block/lime_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pink.png" "$temp_dir/assets/minecraft/textures/block/pink_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_black.png" "$temp_dir/assets/minecraft/textures/block/black_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_brown.png" "$temp_dir/assets/minecraft/textures/block/brown_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_green.png" "$temp_dir/assets/minecraft/textures/block/green_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_white.png" "$temp_dir/assets/minecraft/textures/block/white_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_orange.png" "$temp_dir/assets/minecraft/textures/block/orange_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_purple.png" "$temp_dir/assets/minecraft/textures/block/purple_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_yellow.png" "$temp_dir/assets/minecraft/textures/block/yellow_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_magenta.png" "$temp_dir/assets/minecraft/textures/block/magenta_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_light_blue.png" "$temp_dir/assets/minecraft/textures/block/light_blue_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_silver.png" "$temp_dir/assets/minecraft/textures/block/light_gray_stained_glass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_red.png" "$temp_dir/assets/minecraft/textures/block/red_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_blue.png" "$temp_dir/assets/minecraft/textures/block/blue_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_cyan.png" "$temp_dir/assets/minecraft/textures/block/cyan_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_gray.png" "$temp_dir/assets/minecraft/textures/block/gray_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_lime.png" "$temp_dir/assets/minecraft/textures/block/lime_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_pink.png" "$temp_dir/assets/minecraft/textures/block/pink_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_black.png" "$temp_dir/assets/minecraft/textures/block/black_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_brown.png" "$temp_dir/assets/minecraft/textures/block/brown_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_green.png" "$temp_dir/assets/minecraft/textures/block/green_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_white.png" "$temp_dir/assets/minecraft/textures/block/white_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_orange.png" "$temp_dir/assets/minecraft/textures/block/orange_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_purple.png" "$temp_dir/assets/minecraft/textures/block/purple_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_yellow.png" "$temp_dir/assets/minecraft/textures/block/yellow_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_magenta.png" "$temp_dir/assets/minecraft/textures/block/magneta_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_light_blue.png" "$temp_dir/assets/minecraft/textures/block/light_blue_stained_glass_pane_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/glass_pane_top_silver.png" "$temp_dir/assets/minecraft/textures/block/light_gray_stained_glass_pane_top.png"
  ## wood
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/sapling_acacia.png" "$temp_dir/assets/minecraft/textures/block/acacia_sapling.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/sapling_birch.png" "$temp_dir/assets/minecraft/textures/block/birch_sapling.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/sapling_jungle.png" "$temp_dir/assets/minecraft/textures/block/jungle_sapling.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/sapling_oak.png" "$temp_dir/assets/minecraft/textures/block/oak_sapling.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/sapling_roofed_oak.png" "$temp_dir/assets/minecraft/textures/block/dark_oak_sapling.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/sapling_spruce.png" "$temp_dir/assets/minecraft/textures/block/spruce_sapling.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/slime.png" "$temp_dir/assets/minecraft/textures/block/slime_block.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/planks_acacia.png" "$temp_dir/assets/minecraft/textures/block/acacia_planks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/planks_birch.png" "$temp_dir/assets/minecraft/textures/block/birch_planks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/planks_jungle.png" "$temp_dir/assets/minecraft/textures/block/jungle_planks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/planks_oak.png" "$temp_dir/assets/minecraft/textures/block/oak_planks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/planks_big_oak.png" "$temp_dir/assets/minecraft/textures/block/dark_oak_planks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/planks_spruce.png" "$temp_dir/assets/minecraft/textures/block/spruce_planks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_acacia.png" "$temp_dir/assets/minecraft/textures/block/acacia_log.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_acacia_top.png" "$temp_dir/assets/minecraft/textures/block/acacia_log_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_birch.png" "$temp_dir/assets/minecraft/textures/block/birch_log.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_birch_top.png" "$temp_dir/assets/minecraft/textures/block/birch_log_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_jungle.png" "$temp_dir/assets/minecraft/textures/block/jungle_log.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_jungle_top.png" "$temp_dir/assets/minecraft/textures/block/jungle_log_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_oak.png" "$temp_dir/assets/minecraft/textures/block/oak_log.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_oak_top.png" "$temp_dir/assets/minecraft/textures/block/oak_log_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_big_oak.png" "$temp_dir/assets/minecraft/textures/block/dark_oak_log.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_big_oak_top.png" "$temp_dir/assets/minecraft/textures/block/dark_oak_log_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_spruce.png" "$temp_dir/assets/minecraft/textures/block/spruce_log.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/log_spruce_top.png" "$temp_dir/assets/minecraft/textures/block/spruce_log_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_acacia_lower.png" "$temp_dir/assets/minecraft/textures/block/acacia_door_bottom.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_birch_lower.png" "$temp_dir/assets/minecraft/textures/block/birch_door_bottom.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_jungle_lower.png" "$temp_dir/assets/minecraft/textures/block/jungle_door_bottom.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_wood_lower.png" "$temp_dir/assets/minecraft/textures/block/oak_door_bottom.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_dark_oak_lower.png" "$temp_dir/assets/minecraft/textures/block/dark_oak_door_bottom.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_spruce_lower.png" "$temp_dir/assets/minecraft/textures/block/spruce_door_bottom.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_acacia_upper.png" "$temp_dir/assets/minecraft/textures/block/acacia_door_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_birch_upper.png" "$temp_dir/assets/minecraft/textures/block/birch_door_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_jungle_upper.png" "$temp_dir/assets/minecraft/textures/block/jungle_door_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_wood_upper.png" "$temp_dir/assets/minecraft/textures/block/oak_door_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_dark_oak_upper.png" "$temp_dir/assets/minecraft/textures/block/dark_oak_door_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/door_spruce_upper.png" "$temp_dir/assets/minecraft/textures/block/spruce_door_top.png"
  ## flowers
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_allium.png" "$temp_dir/assets/minecraft/textures/block/allium.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_blue_orchid.png" "$temp_dir/assets/minecraft/textures/block/blue_orchid.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_dandelion.png" "$temp_dir/assets/minecraft/textures/block/dandelion.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_houstonia.png" "$temp_dir/assets/minecraft/textures/block/azure_bluet.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_oxeye_daisy.png" "$temp_dir/assets/minecraft/textures/block/oxeye_daisy.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_paeonia.png" "$temp_dir/assets/minecraft/textures/block/deleted.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_rose.png" "$temp_dir/assets/minecraft/textures/block/poppy.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_tulip_orange.png" "$temp_dir/assets/minecraft/textures/block/orange_tulip.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_tulip_pink.png" "$temp_dir/assets/minecraft/textures/block/pink_tulip.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_tulid_red.png" "$temp_dir/assets/minecraft/textures/block/red_tulip.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/flower_tulip_white.png" "$temp_dir/assets/minecraft/textures/block/white_tulip.png"
  ## crops
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/cocoa_stage_0.png" "$temp_dir/assets/minecraft/textures/block/cocoa_stage0.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/cocoa_stage_1.png" "$temp_dir/assets/minecraft/textures/block/cocoa_stage1.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/cocoa_stage_2.png" "$temp_dir/assets/minecraft/textures/block/cocoa_stage2.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_0.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage0.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_1.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage1.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_2.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage2.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_3.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage3.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_4.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage4.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_5.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage5.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_6.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage6.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/wheat_stage_7.png" "$temp_dir/assets/minecraft/textures/block/wheat_stage7.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/potatoes_stage_0.png" "$temp_dir/assets/minecraft/textures/block/potatoes_stage0.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/potatoes_stage_1.png" "$temp_dir/assets/minecraft/textures/block/potatoes_stage1.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/potatoes_stage_2.png" "$temp_dir/assets/minecraft/textures/block/potatoes_stage2.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/potatoes_stage_3.png" "$temp_dir/assets/minecraft/textures/block/potatoes_stage3.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/carrots_stage_0.png" "$temp_dir/assets/minecraft/textures/block/carrots_stage0.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/carrots_stage_1.png" "$temp_dir/assets/minecraft/textures/block/carrots_stage1.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/carrots_stage_2.png" "$temp_dir/assets/minecraft/textures/block/carrots_stage2.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/carrots_stage_3.png" "$temp_dir/assets/minecraft/textures/block/carrots_stage3.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/nether_wart_stage_0.png" "$temp_dir/assets/minecraft/textures/block/nether_wart_stage0.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/nether_wart_stage_1.png" "$temp_dir/assets/minecraft/textures/block/nether_wart_stage1.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/nether_wart_stage_2.png" "$temp_dir/assets/minecraft/textures/block/nether_wart_stage2.png"
  ## end portal frame
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/endframe_eye.png" "$temp_dir/assets/minecraft/textures/block/end_portal_frame_eye.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/endframe_side.png" "$temp_dir/assets/minecraft/textures/block/end_portal_frame_side.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/endframe_top.png" "$temp_dir/assets/minecraft/textures/block/end_portal_frame_eye.png"
  ## prismarine
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/prismarine_rough.png" "$temp_dir/assets/minecraft/textures/block/prismarine.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/prismarine_rough.png.mcmeta" "$temp_dir/assets/minecraft/textures/block/prismarine.png.mcmeta"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/prismarine_dark.png" "$temp_dir/assets/minecraft/textures/block/dark_prismarine.png"
  ## farmland
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/farmland_dry.png" "$temp_dir/assets/minecraft/textures/block/farmland.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/farmland_wet.png" "$temp_dir/assets/minecraft/textures/block/farmland_moist.png"
  ## tripwire
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/trip_wire.png" "$temp_dir/assets/minecraft/textures/block/tripwire.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/trip_wire_source.png" "$temp_dir/assets/minecraft/textures/block/tripwire_hook.png"
  ## nether portal
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/portal.png" "$temp_dir/assets/minecraft/textures/block/nether_portal.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/portal.png.mcmeta" "$temp_dir/assets/minecraft/textures/block/nether_portal.png.mcmeta"
  ## misc
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/command_block.png" "$temp_dir/assets/minecraft/textures/block/command_block_top.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/brick.png" "$temp_dir/assets/minecraft/textures/block/bricks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/deadbush.png" "$temp_dir/assets/minecraft/textures/block/dead_bush.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/reeds.png" "$temp_dir/assets/minecraft/textures/block/sugar_cane.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/redstone_lamp_off.png" "$temp_dir/assets/minecraft/textures/block/redstone_lamp.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/water_lily.png" "$temp_dir/assets/minecraft/textures/block/lily_pad.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/web.png" "$temp_dir/assets/minecraft/textures/block/cobweb.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/torch_on.png" "$temp_dir/assets/minecraft/textures/block/torch.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/redstone_torch_on.png" "$temp_dir/assets/minecraft/textures/block/redstone_torch.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/tallgrass.png" "$temp_dir/assets/minecraft/textures/block/grass.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/nether_brick.png" "$temp_dir/assets/minecraft/textures/block/nether_bricks.png"
  mv_if_exist "$temp_dir/assets/minecraft/textures/block/quartz_ore.png" "$temp_dir/assets/minecraft/textures/block/nether_quartz_ore.png"
  echo "Zipping..."
  zip -r "$full_path" $temp_dir > /dev/null
  mv "$full_path" $target
else
  echo "$zip with minecraft assets does not exist";
  exit 1;
fi

